name: latent
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - tqdm
  - configargparse
  - python=3.8.5
  - pytorch=1.6.0
  - torchvision=0.7.0
  - scikit-image=0.17.2
  - scikit-learn=0.23.2
